language: node_js
sudo: false
node_js:
  - 'node'
  - 'lts/*'
before_install:
  - npm install -g yarn
script:
  - yarn lint
  - yarn test

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script:
        jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
